### ISSUE TITLE
when I update service name,swarm-listener does not reconfigure docker-flow-proxy

### ISSUE THREAD

**Issue by HappenHaw** [vfarcic/docker-flow-swarm-listener#17]
After I used `docker service update --name new_name old_name` to change serivce name, service can't be accessed.Then,I checked docker-flow-proxy config and logs，docker-flow-proxy removed the config of old_name service，but did not create config for new_name service . I think it have an impact on the high availability. docker version 1.12.6

**Comment by vfarcic** [comment]
I did not foresee that option. I'll start working on adding the support for rename ASAP.

**Comment by HappenHaw** [comment]
Thanks for your reply. As docker 1.13 , flag `--name` was removed. I tried  `docker service update --label-add com.df.servicePath=<..>` to change servicePath, also, swarm-listener didn't deal with it.

**Comment by vfarcic** [comment]
I, kind of, agree with Docker's decision to remove `--name` from `docker service update`. It would be a very dangerous command probably resulting in downtime. It would be equivalent to the `docker service rm` followed with `docker service create` combination.

Swarm listener, at the moment, only notifies the proxy when there is a new service, not when it's updated. I'll work on an improvement so that the listener notifies the proxy whenever there is a change in *com.df* labels.

**Comment by vfarcic** [comment]
I just made a new release 1.8 that should notify the proxy not only when a service is created but also whenever one of the `com.df` labels is added, updated, or removed.

Can you please update your docker-flow-swarm-listener, try it out, and let me know if it works as expected?
