### ISSUE TITLE
Timeout errors

### ISSUE THREAD

**Issue by victor-domain** [vfarcic/docker-flow-swarm-listener#2]
Hey, I been testing this awesome service for the last two days since I replaced my old curl command which was updating my docker-flow-proxy service. However I have noticed a few times during my deployment swarm-listener gives a lot 500 error messages. I wonder if there is some way to troubleshoot at this stage or debug what might be happening? 

This is the last piece I got:

2016/10/20 01:32:30 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app_victor-cicd-XXX&distribute=true&port=80&serviceDomain=XXXXXX.com&servicePath=/ returned status code 500

I also noticed after a while my proxy started to accept traffic but still shows some error 500 messages, however I want to know why doesnt start to accept incoming requests after the service is running on all the nodes (3 at the moment).

**Comment by victor-domain** [comment]
This is how I created my listener:

`docker service create --name swarm-listener \
 --network proxy \
 --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
 -e DF_NOTIF_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure \
 -e DF_NOTIF_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove \
 --constraint 'node.labels.type == manager' vfarcic/docker-flow-swarm-listener`

Proxy:

`docker service create --name proxy \
 -p 80:80 \
 -p 443:443 \
 --network proxy \
 --replicas 3 \
 -e MODE=swarm \
 -e LISTENER_ADDRESS=swarm-listener \
 vfarcic/docker-flow-proxy`

**Comment by vfarcic** [comment]
Status 500 was returned by the proxy. Can you send me the logs from the proxy?

**Comment by Loyz07** [comment]
Hello,

When i try to launch the proxy service i've got this error message:
`Get http://swarm-listener:8080/v1/docker-flow-swarm-listener/notify-services: dial tcp: lookup swarm-listener on 127.0.0.11:53: no such host`

when i try to telnet this port it's closed by default:
```
telnet 127.0.0.11 53
Trying 127.0.0.11...
telnet: Unable to connect to remote host: Connection refused
```

Is it normal ?

Thanks.

**Comment by vfarcic** [comment]
On a first look, seems like the proxy cannot communicate with the listener.
There's probably some problem with the network. Can we connect on Skype or
HangOuts and share your screen?

**Comment by Loyz07** [comment]
Hello Viktor,

It was m'y fault i'd forgotten to change swarm-listener service name in
proxy service configuration.

Sorry for that and thanks for your response.

Regards.

Loïc Guéguen
06 59 51 08 83

Le 7 nov. 2016 12:38 PM, "Viktor Farcic" <notifications@github.com> a
écrit :

> On a first look, seems like the proxy cannot communicate with the listener.
> There's probably some problem with the network. Can we connect on Skype or
> HangOuts and share your screen?
>

**Comment by Loyz07** [comment]
Hello Viktor,

I have an other problem.
When i start my services like this :

docker network create --driver overlay proxy

docker service create \
        --name proxy-swarm-listener \
        --network proxy \
        --mount
"type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
        -e F_NOTIF_CREATE_SERVICE_URL=
http://proxy:8080/v1/docker-flow-proxy/reconfigure \
        -e DF_NOTIF_REMOVE_SERVICE_URL=
http://proxy:8080/v1/docker-flow-proxy/remove \
        --constraint 'node.role==manager' \
        vfarcic/docker-flow-swarm-listener


docker service create \
        --name proxy \
        -p 80:80 \
        -p 443:443 \
        --network proxy \
        -e MODE=swarm \
        -e LISTENER_ADDRESS=proxy-swarm-listener \
        vfarcic/docker-flow-proxy

docker service create \
    --network my_appli \
    --network proxy \
    --name my_appli \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/ \
    --label com.df.serviceDomain=my_appli.mydomaine.com \
    --label com.df.port=3000 \
    --env NODE_ENV=production \
    registry.gitlab.com/my_company/my_appli


I get the error message :

503 Service Unavailable


Could you help me to resolve this error because i can't see where i'm wrong
?


In addition i can say that the DNS domain name is well configured to the
proper ip address and that application port is 3000.

Thanks.




---

*LzIT*

*Loïc Guéguen*
CTO / Lead Developer Web
+33 (0)6 59 51 08 83
loic.gueguen@lzit.fr

2016-11-07 13:12 GMT+01:00 Loïc Guéguen <loic.gueguen@lzit.fr>:

> Hello Viktor,
>
> It was m'y fault i'd forgotten to change swarm-listener service name in
> proxy service configuration.
>
> Sorry for that and thanks for your response.
>
> Regards.
>
> Loïc Guéguen
> 06 59 51 08 83
>
> Le 7 nov. 2016 12:38 PM, "Viktor Farcic" <notifications@github.com> a
> écrit :
>
>> On a first look, seems like the proxy cannot communicate with the
>> listener.
>> There's probably some problem with the network. Can we connect on Skype or
>> HangOuts and share your screen?
>>

**Comment by vfarcic** [comment]
Can we have a chat on Skype or HangOuts and share your screen? I think that will be faster than exchanging logs. If that's not an option, I'll get back to you with commands I'll need to debug the problem.

**Comment by Loyz07** [comment]
Sorry it's not possibe :-(.

I wait for your commands. Thanks.


---

*LzIT*

*Loïc Guéguen*
CTO / Lead Developer Web
+33 (0)6 59 51 08 83
loic.gueguen@lzit.fr

2016-11-07 16:58 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
```sh
docker service update --publish-add 1234:8080 proxy

docker service ps proxy # Wait until it is running

curl [SERVER_IP]:1234/v1/docker-flow-proxy/config

# Find out the node and the ID of the proxy container and enter that machine

docker logs [PROXY_ID]

# Find out the node and the ID of the swarm-listener container and enter that machine

docker logs [SWARM_LISTENER_ID]
```

Those commands should retrieve the config of the proxy, and logs of both services.

**Comment by Loyz07** [comment]
Here are results :

*curl localhost:1234/v1/docker-flow-proxy/config*
global
    pidfile /var/run/haproxy.pid

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  forwardfor
    option  redispatch

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout http-request 5s
    timeout http-keep-alive 15s

    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats auth admin:admin
    stats uri /admin?stats

frontend dummy-fe
    bind *:80
    bind *:443
    option http-server-close
    acl url_dummy path_beg /dummy
    use_backend dummy-be if url_dummy

backend dummy-be
    server dummy 1.1.1.1:1111 check


*docker logs proxy.1.36tc6v9gkg4r9fm1ss63nup0n *
2016/11/07 16:08:16 Starting HAProxy
2016/11/07 16:08:16 A request was sent to the Swarm listener running on
http://proxy-swarm-listener:8080. The proxy will be reconfigured soon.
2016/11/07 16:08:16 Starting "Docker Flow: Proxy"
2016/11/07 16:09:04 Processing request /v1/docker-flow-proxy/config

*docker logs proxy-swarm-listener.1.50iuivlbj7cyef790ube7gzlu*
2016/11/07 09:43:00 Starting Docker Flow: Swarm Listener
2016/11/07 09:43:00 Starting iterations
2016/11/07 16:08:16 Sending service created notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/
2016/11/07 16:08:16 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:08:21 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:08:26 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:08:31 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:08:36 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:08:41 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:08:46 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:08:51 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:08:56 Notification to
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/ failed. Retrying...
2016/11/07 16:09:01 ERROR: Get
?serviceName=utocat-web-application&distribute=true&port=3000&serviceDomain=
qualif.www.utocat.com&servicePath=/: unsupported protocol scheme ""

I can see the error but protocol is HTTP so.... I think it's supported ;-).


---

*LzIT*

*Loïc Guéguen*
CTO / Lead Developer Web
+33 (0)6 59 51 08 83
loic.gueguen@lzit.fr

2016-11-07 17:07 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
Can you double check the swarm-listener environment variables. From the commands you listed, seem you're missing the letter D. There is `-e F_NOTIF_CREATE_SERVICE_URL=` instead `-e DF_NOTIF_CREATE_SERVICE_URL=`.

**Comment by Loyz07** [comment]
Hello Viktor,

It works now.
I'm sooooooooo sorry.
Bib big thanks for your help, for your reactivity and FOR THIS AMAZING
service !




---

*LzIT*

*Loïc Guéguen*
CTO / Lead Developer Web
+33 (0)6 59 51 08 83
loic.gueguen@lzit.fr

2016-11-07 17:50 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
You're welcome.

I'll close the ticket. If you have any other problem, please reopen it or create a new one.

**Comment by Loyz07** [comment]
Hello Viktor,


I face a new problem with docker-flow:proxy.

I would like to proxy many websites with each a different domain name and
SSL certificate.
Is-it possible to use automatic configuration for this ?
Could you show me the way to configure the proxy if it's possible ?

The only solution i found for now is to manually configure the proxy and
add the right certificate for each site in the HAproxy config.

Thanks.



---

*LzIT*

*Loïc Guéguen*
CTO / Lead Developer Web
+33 (0)6 59 51 08 83
loic.gueguen@lzit.fr

2016-11-07 18:08 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
At the moment, there is only the option to have certificates applied to all services (websites). If that would work for you (normally you would have a wildcard certificate), I can show you how to add it.

In parallel, I started working on an API that will allow you to upload certificates and avoid messing with configuration files. The first release that will also have certificates applied globally will be available soon (in a few days). After that, if global certificates do not fit your needs, I can make changes to that they are applied on per service basis.

Please let me know your thoughts and we'll move it from there.

**Comment by Loyz07** [comment]
Hello Viktor,

i update the line :
*bind *:443 *
by


*bind *:443 ssl crt /etc/ssl/private/*
in haproxy.cfg file inside the container and add my certs in
/etc/ssl/private and all work fine.

But when a service is updated the line returns to : *bind *:443*

So I suggest this solution :

   1. modify default line to *bind *:443 ssl crt /etc/ssl/private/*
   2. add* 'com.df.serviceCert'* label with value of the needed certificate
   in service definition. This label is use to create a file name with the
   domainName of the service .pem in /etc/ssl/private/

*warning*: the value of com.df.serviceCertificate must be the concatenation
of the .crt and the .key file of the certificate. which you can obtain with
the command : cat my-domain.crt my-domain.key > my-domain.pem or this
operation can be done by docker-flow:proxy if we add  label :
com.df.serviceSslCert and com.df.serviceSslKey.

At your disposal for more information.




---

*LzIT*

*Loïc Guéguen*
CTO / Lead Developer Web
+33 (0)6 59 51 08 83
loic.gueguen@lzit.fr

2016-11-10 16:40 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
At the moment (until I finish the new certs API), you should modify the haproxy.tmpl file. The proxy generates a new haproxy.cfg every time a new service is reconfigured (or removed). The haproxy.tmpl is used as the base so that's the correct file to modify. I think that the best way would be to create a new container using vfarcic/docker-flow-proxy as the base and with the added cert file and modified template.

A very short info is at the bottom of the [container config](https://github.com/vfarcic/docker-flow-proxy#container-config) section.

That was the present...

The problem with your approach (if I understood it correctly) is that you'd still need to provide the cert file somehow. That would mean building a new image or mounting a volume. If you mount a volume on a host, you'd need to make sure it is available on all servers since you don't know where will Swarm schedule replicas.

In case you don't want to build a new image, the idea is to use an API to upload certs. That way, you can change it whenever needed without rebuilding the image. The proxy would make sure that the certs are always distributed across all replicas. Do you think that would be a good idea?

**Comment by Loyz07** [comment]
cool we have a solution for now ;-).

Concerning :
*The problem with your approach (if I understood it correctly) is that
you'd still need to provide the cert file somehow. That would mean building
a new image or mounting a volume. If you mount a volume on a host, you'd
need to make sure it is available on all servers since you don't know where
will Swarm schedule replicas.*

Sorry for my poor english, here is an example of what i suggest to create a
service with a specific certificate :

docker service create \
    --network $APP_NETWORK_NAME \
    --network proxy \
    --name $APP_SERVICE_NAME \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.serviceDomain=$APP_DOMAIN_NAME \
    --label com.df.servicePath=/ \
    --label com.df.port=$APP_PORT \
    --label com.df.serviceCertificate=$APP_CERTIFICATE \
    $APP_DOCKER_IMAGE_NAME

with

$APP_CERTIFICATE=`cat /etc/ssl/private/my-domain.pem` with /etc/ssl/private
mounted to a HAnas or whatever
or
$APP_CERTIFICATE = an environment variable of the host initate with ansible
script or whatever
or
$APP_CERTIFICATE = a request to a vault server

In my side, i'havent anderstood your proposition with certificate API.

Thanks.



---

*LzIT*

*Loïc Guéguen*
CTO / Lead Developer Web
+33 (0)6 59 51 08 83
loic.gueguen@lzit.fr

2016-11-10 18:11 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
Now I get it. You mean to put the content of a certificate inside the com.df.serviceCertificate label?

I think that a certificate is too big to be placed as a label. To make things more complicated, there could be multiple certificates and Docker probably has a limit on label size. I'm not even sure it allows all the characters (e.g. new lines) as labels. Also, having labels like that would complicate monitoring since most tools these days use labels to get info.

I think it would be better if a certificate file is inside container; either by making a new image with the certificate baked in or by adding it to a running container. The first option is easy and can be done now. The second is a bit more complicated when running inside a Swarm cluster (multiple replicas distributed across multiple nodes, not fault tollerant, ...).

What I'm thinking with an API would be something like:

```sh
curl -i -XPUT \
    --data-binary @tmp/xip.io/xip.io.pem \
    $(docker-machine ip docker-flow-proxy-tests):8080/v1/docker-flow-proxy/cert?certName=xip.io.pem
```

That request would send a signal that you want to add xip.io.pem as a certificate. Contents of the file are sent with the request and the proxy would download it, store it as a file, and change the config. Also, it would make sure that all the replicas get the same certificate.

The second option is to create your own image based on the vfarcic/docker-flow-proxy that already has the certificate inside and labels only for the names of certificate files so that it knows how to generate the configuration.

Both approaches can be combined if needed. You can have an image with certificates inside and add more later through PUT requests.

I'm not discarding your approach either. We can test whether labels can accept certificate content. If they can, that would be the third option.

What do you think? Please let me know if I managed to explain the idea behind the API.

**Comment by Loyz07** [comment]
All is clear now.
Let me think about theses options.

Thanks for your job and your answers.

Loïc Guéguen
06 59 51 08 83

Le 10 nov. 2016 7:12 PM, "Viktor Farcic" <notifications@github.com> a
écrit :

**Comment by vfarcic** [comment]
I made the first version of the idea. Can you take a look at https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode-listener.md#configuring-service-ssls-and-proxying-https-requests and let me know what you think?

**Comment by Loyz07** [comment]
Hello Viktor,

It's work fine !

.... but only for one cert ;-) !

I think it would be more flexible to fix the line in haproxy.cfg to

*bind *:443 ssl crt /certs/*

then the command



*curl -i -XPUT \    --data-binary @tmp/xip.io.pem \    "$(docker-machine ip
node-1):8080/v1/docker-flow-proxy/cert?certName=xip.io.pem&distribute=true"*

will create a new cert in /certs/ directory

so that proxy can use multiples certs for all its servicies.

What do you think ?

Thanks.


---

*LzIT*

*Loïc Guéguen*
CTO / Lead Developer Web
+33 (0)6 59 51 08 83
loic.gueguen@lzit.fr

2016-11-14 2:11 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
I thought to do it like that. However, soon I'll extend it in a way that a certificate can be added as global (for all services, as it is now), or per service. That's why I choose to specify certificates explicitly.

As for ".... but only for one cert ;-) !", that's not true. You can put as many certificates as you want. Try to send two PUT requests with two different certificates and you'll see that they are both added to the proxy configuration. At least, that was the intention behind the latest release. If it doesn't work like that, it's a bug.

**Comment by Loyz07** [comment]
Hello Viktor,

Sorry, you're right, i'haven't tried to put more than one certificate.

I'll try it tomorrow.

For information, for production usage i think i won't use the API but an HA
NAS to share certificates because it's easier to manage and we already need
a NAS to share other data between all hosts.

Thanks.

Loïc Guéguen
06 59 51 08 83

**Comment by vfarcic** [comment]
Shared volume with certificates is a good option.

I'll close the ticket. Feel free to reopen it if you encounter a problem.
