### ISSUE TITLE
Support for Container Added / Container Removed

### ISSUE THREAD

**Issue by s4s0l** [vfarcic/docker-flow-swarm-listener#20]
Could extract container information from dockers /tasks api and work exactly as notifications about services.

Why: While i struggle with docker in swarm mode and docker in general tools like https://github.com/jwilder/docker-gen are a must for many applications (see haproxy:)) I've tweaked docker-gen, which didn't support swarm mode, to extract containers from tasks api and pointed my docker-gen containers to docker endpoints on manager nodes (exposed via socat), because docker does not support events regarding swarm these docker-gen images needed to poll for changes. Because docker-gen needs to write some files for some services which location is unknown (due to lack of container affinity in swarm) I run docker-gen globaly and host mount files. It's ugly. With that i can live, but when there is a lot of worker nodes it starts to generate some load. So I started to rewrite it, so that some containers will push changes to docker-gen based containers. At this point I felt so frustrated I started to search for someone who has done it already. Thats how I found docker-flow projects. I love it. But it does not solve my case:/ But it is so close. 

Have you considered dfsl to be some kind of general purpose docker event dispatcher? 

Another thing maybe for another issue but could Notify*Urls be an list? List of names that could be further splitted to SRV dns entries. Currently as i understand DFSL notifies one DFP and DFP broadcasts it further. This reduces re usability of DFSL alone.

Totally awesome would be to ask DFSL to broadcast changes to all containers/services with given label/labels. This way these listening containers/services could show up dynamically with no change to DFSL configuration.

**Comment by vfarcic** [comment]
The idea behind DFSL was from the beginning to make it general. However, I never got enough time and, more importantly, enough use cases to make it like that. So, I started by making it work with DFP while having in mind that the design should be general. At the moment, it could be used with any service (not only DFP). The problem, as you noted, is that it allows only a single URL in `DF_NOTIFY_CREATE_SERVICE_URL` and `DF_NOTIFY_REMOVE_SERVICE_URL` env. vars. I'll change that right away (expect a new release today).

Since I started with DFP use case, I did not (yet) contemplate other use cases. Splitting to SRV DNS entries is a good one as well as using labels to get URLs where those notifications should be sent.

Can we do the following? I'll start work on allowing comma separated list of values in `DF_NOTIFY_CREATE_SERVICE_URL` and `DF_NOTIFY_REMOVE_SERVICE_URL` env. vars., consider this issue as a request, and close it once it's done. Can you open new issue for the other requests you mentioned (or any other you might have)? That way, it is easier for me to track what should be done and we can have a separate discussion focused on each feature. Does that sound OK?

P.S. I'd be more than happy if you could do PRs as well :)

**Comment by vfarcic** [comment]
The first request that adds the feature to have multiple notification addresses is finished. It's available as release [1.13](https://github.com/vfarcic/docker-flow-swarm-listener/releases/tag/1.13). You can find more info in [sending notification requests to multiple destinations](https://github.com/vfarcic/docker-flow-swarm-listener#sending-notification-requests-to-multiple-destinations) example as well as [configuring docker flow proxy](https://github.com/vfarcic/docker-flow-swarm-listener#configuring-docker-flow-proxy) sections of the [README](https://github.com/vfarcic/docker-flow-swarm-listener/blob/master/README.md).

Please let me know if this is what you were looking for and if you're OK with opening new issues for the rest of requests.

**Comment by s4s0l** [comment]
Thats great. For now it's ok for me.
It was late yesterday when I filed this issue. As I look at it now it seems I've dumped here my stack before going to sleep. I think I'll rethink it and maybe collect some more concrete requirements.

**Comment by vfarcic** [comment]
Please do. The suggestions you made are great and I'd like to have the implemented in DFSL.
