### ISSUE TITLE
Use container's EXPOSE directive if no com.df.port is specified

### ISSUE THREAD

**Issue by zarbis** [vfarcic/docker-flow-swarm-listener#33]
Currently if no `com.df.port` label is specified DFSL will panic with `"When MODE is set to \"service\" or \"swarm\", the port query is mandatory"`.
It could use `EXPOSE` directive from `Dockerfile` that appears as `Config.ExposedPorts` in both `docker image inspect` or `docker container inspect` (but not in `docker service inspect`).
If only a single port is `EXPOSE`d - it is probably right port to use and is sensible default.

So the order should be:
1) use explicitly declared `com.df.port`
2) use `EXPOSE`d port if only one is defined
3) panic otherwise

**Comment by vfarcic** [comment]
I explored the API and, from what I've seen, exposed ports are not available on the service level. I don't think that this could be done so I'll close the issue. If anyone finds a way to get this info from a service, I'd be more than happy to add this feature to the project. It's a pity since it would be very useful and would simplify the process.
