### ISSUE TITLE
Filtered notifications

### ISSUE THREAD

**Issue by valeriomazzeo** [vfarcic/docker-flow-swarm-listener#39]
Since it is possible to specify multiple notifications URLs, it would be great if it was possible to specify also multiple notify labels to match with the URLs.

For example, I’d like the listener to notify the proxy for certain services and another container for others.

Although, on my container I can filter the services I am not interested to, I am a bit concerned about sending unneeded notifications to the proxy.

**Comment by vfarcic** [comment]
That would be an interesting addition. However, I'm not sure how to distinguish where would each notification go in a way that is generic and not tied to a specific end-point (e.g., DFP). The information about notification URLs is in DFSL while the information is in service labels. Maybe it would make sense to have a service label like `com.df.notifyService=my-service` and send that to those services that have `my-service` as domain/DNS. So, it DFSL has `      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure,http://my-service:8080/v1/docker-flow-proxy/reconfigure`, a notification would be sent only to the latter address since it's domain/DNS is `my-service`.

What do you think? Do you have a better idea how it could be done? Would you like to give it a try yourself and send a PR?

**Comment by valeriomazzeo** [comment]
I think your solution would be good, but `com.df.notifyService=my-service` has to be able to specify multiple services, perhaps comma separated

**Comment by vfarcic** [comment]
I don't think I'll have free time for the next 10 days. Would you like to give it a try with a PR?

**Comment by valeriomazzeo** [comment]
Unfortunately, I am not really proficient with GO.

Don't worry and take your time, I am not in need of this feature, I just thought it was a good one to have.

**Comment by vfarcic** [comment]
Available in `vfarcic/docker-flow-swarm-listener:18.01.06-29`. Can you please try it out and let me know if it works as expected? You'll just have to add `com.df.notifyService` with the name of the service that should be notified. Multiple values can be separated with comma (`,`). Please note that the service still needs to be defined as one of the `DF_NOTIFY_CREATE_SERVICE_URL` values.
